/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        /* ---- Material 3 Design Tokens (from Stitch) ---- */
        "inverse-on-surface": "#f3f0f2",
        "primary-fixed-dim": "#65d8d7",
        "surface-container-highest": "#e4e2e4",
        "tertiary-fixed-dim": "#b8cbbf",
        "on-secondary-container": "#21703f",
        "on-surface-variant": "#3d4949",
        "secondary": "#1b6c3b",
        "tertiary-container": "#67796e",
        "surface": "#fcf8fb",
        "on-secondary-fixed-variant": "#005228",
        "inverse-surface": "#303032",
        "on-tertiary-container": "#f5fff7",
        "on-secondary-fixed": "#00210c",
        "on-secondary": "#ffffff",
        "tertiary-fixed": "#d4e7da",
        "error": "#ba1a1a",
        "outline-variant": "#bcc9c8",
        "background": "#fcf8fb",
        "on-surface": "#1b1b1d",
        "secondary-fixed": "#a4f4b6",
        "outline": "#6d7a79",
        "on-primary": "#ffffff",
        "primary-fixed": "#83f4f4",
        "on-primary-container": "#f3fffe",
        "on-error-container": "#93000a",
        "inverse-primary": "#65d8d7",
        "surface-variant": "#e4e2e4",
        "on-primary-fixed": "#002020",
        "on-primary-fixed-variant": "#004f50",
        "surface-container-lowest": "#ffffff",
        "on-tertiary": "#ffffff",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "secondary-container": "#a2f2b3",
        "surface-tint": "#006a6a",
        "surface-container": "#f0edef",
        "on-tertiary-fixed-variant": "#3a4a41",
        "surface-container-low": "#f6f3f5",
        "surface-bright": "#fcf8fb",
        "on-background": "#1b1b1d",
        "primary-container": "#008282",
        "primary": "#006767",
        "secondary-fixed-dim": "#89d89c",
        "on-tertiary-fixed": "#0f1f17",
        "surface-dim": "#dcd9dc",
        "surface-container-high": "#eae7ea",
        "tertiary": "#4f6056",

        /* ---- Brand Accent Colors ---- */
        "brand-sage": "#E2F5E8",
        "brand-teal": "#18A0A0",
        "brand-charcoal": "#333333",
        "brand-forest": "#1b6c3b",

        /* ---- Semantic aliases ---- */
        "accent": "#18A0A0",
        "accent-hover": "#14888A",
        "accent-light": "#E8F7F7",
        "on-accent": "#FFFFFF",
        "danger": "#E5534B",
        "online": "#22C55E",
        "delivered": "#A8A8AB",
        "read": "#18A0A0",
        "text-primary": "#1C1C1E",
        "text-secondary": "#6B6B6E",
        "text-muted": "#9D9DA0",
        "border": "#E5E5E3",
        "bubble-sent": "#E2F5E8",
        "bubble-recv": "#FFFFFF",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
        bubble: "20px",
      },
      spacing: {
        "margin-mobile": "16px",
        md: "16px",
        xl: "40px",
        lg: "24px",
        sm: "8px",
        "margin-desktop": "32px",
        xs: "4px",
        unit: "4px",
        gutter: "20px",
      },
      fontFamily: {
        "headline-md": ["DM Sans", "sans-serif"],
        "display-lg": ["Literata", "Georgia", "serif"],
        "label-md": ["Geist", "system-ui", "sans-serif"],
        "headline-lg": ["DM Sans", "sans-serif"],
        "body-md": ["DM Sans", "sans-serif"],
        "body-lg": ["DM Sans", "sans-serif"],
        "label-sm": ["Geist", "system-ui", "sans-serif"],
        sans: ["DM Sans", "system-ui", "sans-serif"],
        serif: ["Literata", "Georgia", "serif"],
      },
      fontSize: {
        "headline-md": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "500" }],
        "display-lg": ["48px", { lineHeight: "1.2", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.02em", fontWeight: "500" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "500" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
      },
      boxShadow: {
        bubble: "0 1px 3px rgba(0,0,0,0.06)",
        card: "0 2px 8px rgba(0,0,0,0.06)",
        modal: "0 8px 32px rgba(0,0,0,0.12)",
      },
      keyframes: {
        "bounce-dot": {
          "0%, 80%, 100%": { transform: "scale(0)" },
          "40%": { transform: "scale(1)" },
        },
        "fade-in": {
          "0%": { opacity: "0" },
          "100%": { opacity: "1" },
        },
        "fade-in-down": {
          "0%": { opacity: "0", transform: "translateY(-10px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        "bounce-subtle": {
          "0%, 100%": { transform: "translateY(0)" },
          "50%": { transform: "translateY(-5%)" },
        }
      },
      animation: {
        "bounce-dot": "bounce-dot 1.4s ease-in-out infinite both",
        "fade-in": "fade-in 0.5s ease-out",
        "fade-in-down": "fade-in-down 0.5s ease-out",
        "bounce-subtle": "bounce-subtle 2s infinite ease-in-out",
      },
    },
  },
  plugins: [],
}
